excluded:
    # - Pods
cyclomatic_complexity:
  warning: 20
  error: 30
disabled_rules:
    # - trailing_newline
    # - closure_end_indentation
    # - closure_parameter_position
    # - closure_spacing
    # - opening_brace
    # - empty_count
    # - comma
    # - colon
    # - force_cast
    # - type_name
    # - trailing_semicolon
    # - force_try
    # - function_body_length
    # - nesting
    - variable_name
    # - operator_whitespace
    # - control_statement
    # - legacy_constant
    - line_length
    # - return_arrow_whitespace
    - trailing_whitespace
    - empty_parentheses_with_trailing_closure
    # - closing_brace
    # - statement_position
    # - type_body_length
    # - todo
    # - legacy_constructor
    # - valid_docs
    # - missing_docs
    # - file_length
    # - leading_whitespace
identifier_name:
    excluded: id # 允许命名为id
